development:
 <<: *default
 database: try_development
 host: localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock

test:
 <<: *default
 database: try_test
 host: localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock

production:
 <<: *default
 database: try_production
 host:localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock