default: &default
 adapter: mysql2
 encoding: utf8
 reconnect: false
 pool: 5
 timeout: 5000

development:
 <<: *default
 database: try_development
 host: localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock

test:
 <<: *default
 database: try_test
 host: localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock

production:
 <<: *default
 database: try_production
 host: localhost
 username: root
 password: password
 socket: /var/run/mysqld/mysqld.sock